name: build-%SYSTEM_NAME%-%TEAM_NAME%
on:
  push:
    branch: development
  workflow_dispatch:
jobs:
  build-from-source:
    uses: ga-framework-poc/cicd-manager/.github/workflows/build-from-source.yml@development
    with:
      system-name: %SYSTEM_NAME%
    secrets: inherit
  deploy-to-all:
    needs: build-from-source
    uses: ga-framework-poc/cicd-manager/.github/workflows/promote.yml@development
    with:
      system-name: %SYSTEM_NAME%